### PR TITLE
Fixed Python 2.7 Support

### PR DESCRIPTION
**Pull request by niemasd**
I've updated print statements and whatnot to fix Python 2.7 support. Note that I haven't actually tested this on a dataset: I've just edited until no more errors are thrown when I try to run it (i.e., I successfully make it to the help screen), so more testing would be good before it's integrated

### CODE REVIEW

**Comment by stevenweaver** [comment]
Dear @niemasd, 

Thank you for this PR. We'll need to add Python 2.7 to the travis.ci build matrix before accepting. In addition, there appears to be an outstanding issue with strip_drams. 

Best,
Steven

**Comment by niemasd** [comment]
I've made a change that *should* fix the strip_drams issue. Thanks!

**Comment by stevenweaver** [comment]
Dear @niemasd, 

While the PR builds, porting hivtrace and its dependencies looks to be a pretty large undertaking, in large part thanks to `BioExt`. January 1st, 2020 marks the end of life for Python 2. I think it may be best to maintain only Python 3 support, despite the current issue with Python 3.7 compatibility. 

I'm going to close this PR, but I appreciate it.  

Best,
Steven

**Comment by niemasd** [comment]
Sure, that's fair enough! Thanks!

**Pull request closed without merging**
