### PR TITLE
Create devcontainer.json

### PR DESCRIPTION
**Pull request by niemasd**
With this devcontainer file, VS Code (and GitHub Codespaces) will be able to create the development environment automatically.

### CODE REVIEW

**Comment by niemasd** [comment]
@stevenweaver This one has now been ported to Oracle Linux and has been tested. I'm able to successfully compile and run HIV-TRACE from the Docker environment via `python3 setup.py develop`.

Note that this Dockerfile has the tn93 patch regarding OpenMP compatibility. I've documented it in the Dockerfile, and we should delete it once the tn93 code is patched

**Comment by stevenweaver** [comment]
@niemasd -- Is it OK to remove the `sed` commands now?

**Comment by niemasd** [comment]
I hadn't heard back re: this question yet:

https://github.com/veg/tn93/pull/34#issuecomment-1817191251

So I'll go ahead and assume option 2 (using the GCC version update you suggested). So I'll do the following:

1. Update the tn93 `Dockerfile` to use the updated GCC version fix you found and create a new PR
2. Update the other repos' `Dockerfile`s to incorporate this fix as well
  * I'll comment on those repos' PRs to let you know when I've tested them and confirmed that the `Dockerfile` works successfully

**Comment by stevenweaver** [comment]
Thanks Niema, I missed that question.

**Comment by niemasd** [comment]
No worries 😄

**Comment by niemasd** [comment]
@stevenweaver This PR is ready as of the following commit:

https://github.com/niemasd/hivtrace/commit/a12422f4601f91fd5ba19c13c1fb8e7ffe8a1823

The above commit fixes the `Dockerfile` such that the tn93 compilation fix for the CMake GCC-10 issue we discussed is incorporated.

**Pull request merged**
